export const FILTER_CHANGE = 'FILTER_CHANGE';
export const PAGINATION_CHANGE = 'PAGINATION_CHANGE';

export const REQUEST_ARTICLES = 'REQUEST_ARTICLES';
export const RECEIVE_ARTICLES = 'RECEIVE_ARTICLES';

export const REQUEST_ARTICLE = 'REQUEST_ARTICLE';
export const RECEIVE_ARTICLE = 'RECEIVE_ARTICLE';

